### PR TITLE
Add compatibility for DigitalOcean Spaces

### PR DESCRIPTION
**Pull request by riversteve**
This add compatibility for hosting on DigitalOcean.

There are two new variables introduced to the config/env file` (HOST_REGION, HOST_PROVIDER)`. I made the default values in the config/env.example for AWS.  There are certain AWS features that DigitalOcean Spaces is not compatible with, so I made a separate `do-ensure-bootstrap` with the incompatible pieces removed.

I do not currently have an AWS account so please test these changes work for you.  They should, but please verify.

### CODE REVIEW

**Comment by riversteve** [comment]
https://docs.aws.amazon.com/general/latest/gr/s3.html
`s3.amazonaws.com` should work as a default endpoint on AWS, since this is a lightweight deploy.  Users could also hardcode `AWS_S3_ENDPOINT` in Makefile to whatever they choose.

**Comment by J-Swift** [comment]
Awesome! Thanks for this. I've actually been reworking the deployment behind the scenes to be more agnostic / flexible, so I'm going to keep this PR open until I can push that work. Then I'll rebase this effort on top of that. The downside is that you might need to tweak some of your local configuration to be compatible with the new format but hopefully it isn't too bad.

**Comment by BoweFrankema** [comment]
Hi @riversteve, thanks for building this! Are you still planning to rework this? I've tried to set it up on a Digital Ocean Droplet with Ubuntu 20.04 + Docker pre-installed but could not figure it out sadly. I wish there was an easier way to get this going, but I understand it'll take a lot of time. I basically got stuck at trying to figure out how to make "Make" work. i.e

make: *** No rule to make target 'docker-query-player'.  Stop.

**Comment by J-Swift** [comment]
@BoweFrankema make sure you are issuing the `make` command from the same directory as the `Makefile`. That sounds like you might be in a different directory.

**Comment by BoweFrankema** [comment]
Alright I made some progress! One question about the AWS credentials.. are there any specific access rights I have to allow the IAM user to use this?

**Comment by J-Swift** [comment]
S3 related stuff and probably some other random bits, I'd have to deep dive a bit to see exactly what is relied on. The current S3 deployment is static though so you should be good to use an elevated admin account to perform the setup and deployment if you run into IAM issues.

**Comment by BoweFrankema** [comment]
Yep I just used an elevated admin account.. Now also got the API queries to work thanks to your tips. Thank you, and once I got it working I'd love to send you a small donation :-)

**Comment by BoweFrankema** [comment]
It works! Thank you so much, super nice! https://floppy-cod-stats.s3.eu-central-1.amazonaws.com/index.html

**Comment by riversteve** [comment]
I should have made this PR from its own branch instead of master.  My other SSO changes are now part of this too, whoops.

I made a separate PR for only the SSO updates => https://github.com/J-Swift/cod-stats/pull/5

**Comment by riversteve** [comment]
Closing this PR for my master branch and reopened at https://github.com/J-Swift/cod-stats/pull/6

**Pull request closed without merging**
